### ISSUE TITLE
Ongoing issue/idea chat

### ISSUE THREAD

**Issue by drop-table-lol** [drspaceman0/Python-Game#21]
We need some sort of chat client or place that we can have for game ideas that we both check regularly, where we can throw ideas at the proverbial wall, see what sticks, then comment on, make fun of, dissect, etc each other's ideas and then put them into code

**Comment by eric-marsh** [comment]
Like Facebook messenger? Or more like Cloud9?

**Comment by drop-table-lol** [comment]
Yeah, either of those work
